server:
  port: 8081

spring:
  application:
    name: activity-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/activity_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:-https://clerk.aqtilink.live/.well-known/jwks.json}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /activity-docs/swagger-ui.html
  api-docs:
    path: /activity-docs/v3/api-docs

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000,https://aqtilink.live}

service:
  api-key: ${SERVICE_API_KEY:key-is-in-env}

user-service:
  url: ${USER_SERVICE_URL:http://localhost:8080}
